server:
  port: 9094
spring:
  h2:
    console:
      settings:
        trace: true  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: ${EUREKA_URI:http://localhost:9090/eureka}
  server:
    enableSelfPreservation: false
    wait-time-in-ms-when-sync-empty: 3000
